@extends('layout.template')

@section('content')
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1.</td>
                <td>Shelamita</td>
                <td>517749</td>
                <td>A</td>
            </tr>
            <tr>
                <td>2.</td>
                <td>Novita</td>
                <td>522289</td>
                <td>A</td>
            </tr>
            <tr>
                <td>3.</td>
                <td>Shafa</td>
                <td>519778</td>
                <td>A</td>
            </tr>
            <tr>
                <td>4.</td>
                <td>Aul</td>
                <td>534723</td>
                <td>A</td>
            </tr>
        </tbody>
    </table>
@endsection
